#!/system/bin/sh
make -j4;
cp drivers/net/wireless/bcm4329/bcm4329.ko ../bcm4329.ko;
make clean;
make -j4 CFLAGS=-"-O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -pipe";
cp arch/arm/boot/zImage ../zImage;
make clean;
